### Role Name

Pre-flight retrieves various assets from the bastion host:

- ec2-user ssh key for authentication to target hosts:
- repo-file: retrieves and stores bastion's repo file for population to target hosts
- (populates local ~/.ssh and sets permissions)

### Requirements

Any pre-requisites that may not be covered by Ansible itself or the role should be mentioned here. For instance, if the role uses the EC2 module, it may be a good idea to mention in this section that the boto package is required.

### Role Variables

repofile: holds the name of the repo file to retrieve from bastion:/etc/yum.repo.d 

A description of the settable variables for this role should go here, including any variables that are in defaults/main.yml, vars/main.yml, and any variables that can/should be set via parameters to the role. Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.) should be mentioned here as well.

Dependencies
------------

None. Typically the common role would need pre-flight to run first to acquire
 assets
A list of other roles hosted on Galaxy should go here, plus any details in regards to parameters that may need to be set for other roles, or variables that are used from other roles.

Example Playbook
----------------

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

- name: pre-flight, retrieve assets from bastion host
  hosts: bastion
  become: yes
  gather_facts: false
  vars:
    repofile: open_three-tier-app.repo

  roles:
    - {name: pre-flight, tags: [pre-flight]}


License
-------

BSD

Author Information
------------------

An optional section for the role authors to include contact information, or a website (HTML is not allowed).
